version: '1.0'
name: pipeline-20211218
displayName: pipeline-20211218
triggers:
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-96e1eb6a
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@php
        name: build_php
        displayName: PHP 构建
        phpVersion: '8.0'
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        commands:
          - php --version
permissions:
  - role: admin
    members: []
